name:                starter-example
version:             0.1.0
author:              "Raghu Kaippully"
maintainer:          "rkaippully@gmail.com"
copyright:           "2018 Raghu Kaippully"

dependencies:
  - base >= 4.7 && < 5
  - starter

executables:
  starter-example:
    main:         Main.hs
    source-dirs:  app
    other-modules:
      - App
    dependencies:
      - base >= 4.7 && < 5
      - Spock >= 0.11
      - mtl
      - text
      - starter
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
