name:                starter
version:             0.1.0
github:              "rkaippully/starter"
license:             MPL-2.0
author:              "Raghu Kaippully"
maintainer:          "rkaippully@gmail.com"
copyright:           "2018 Raghu Kaippully"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Develop applications without restarts
category:            Web
description:         Please see the README on Github at <https://github.com/rkaippully/starter#readme>

dependencies:
  - base >= 4.7 && < 5
  - fsnotify >= 0.2.1 && < 0.3

library:
  source-dirs: src
